### PR TITLE
Looking up ROR display name for top ID in prediction

### PR DESCRIPTION
**Pull request by Whattabatt**
To make incorporating linking RORs to affiliations in corpus/ES easier. https://github.com/allenai/scholar/issues/33727

### CODE REVIEW

**Comment by sergeyf** [comment]
As discussed on Slack. TODO:

1. Fix bug with re-instantiating ror_index.
2. Rerun TIMO tests.

**Review by sergeyf — CHANGES_REQUESTED** [review]
Fix ror_index issue

**Review by sergeyf — APPROVED** [review]
Feel free to merge if TIMO tests pass

**Comment by Whattabatt** [comment]
With new change test script works as intended and tt verify passes

**Pull request merged**
